import pytest

from mermin_corpus.errors import ManifestError
from mermin_corpus.manifest import load, validate_entry

SAMPLE = """\
schema = 1
root = "/mnt/ASF-EX1/mermin-corpus"

# a comment that must survive a round trip
[[entry]]
id = "phantom-uniform"
rung = 0
partition = "commercial-safe"
access = "OPEN"
licence = "CC0-1.0"
attribution = "generated by mermin_corpus.phantoms"
doi = ""
retain_raw = true

[entry.source]
kind = "generated"
generator = "uniform_director"
seed = 20260802

[entry.expected]
axes = ""
shape = []
dtype = ""
size_c = 0
pixel_size_um = 0.0
reader = ""

[entry.roles]
nuclear = { by = "index", value = 0 }
fibre = { by = "index", value = 1 }

[entry.policy]
projection = "single"
z = 0
t = 0

[entry.provenance]
access_date = ""
raw_sha256 = ""
raw_bytes = 0
status = "pending"
"""


@pytest.fixture()
def manifest_file(tmp_path):
    p = tmp_path / "manifest.toml"
    p.write_text(SAMPLE)
    return p


def test_load_reads_entries(manifest_file):
    m = load(manifest_file)
    assert m.schema == 1
    assert [e.id for e in m.entries] == ["phantom-uniform"]
    assert m.get("phantom-uniform").source["kind"] == "generated"


def test_get_raises_on_unknown_id(manifest_file):
    with pytest.raises(ManifestError, match="unknown entry"):
        load(manifest_file).get("nope")


def test_update_provenance_round_trips_and_keeps_comments(manifest_file):
    m = load(manifest_file)
    m.update_provenance("phantom-uniform", raw_sha256="abc", raw_bytes=7, status="fetched")
    m.save()
    text = manifest_file.read_text()
    assert "a comment that must survive a round trip" in text
    reloaded = load(manifest_file)
    assert reloaded.get("phantom-uniform").provenance["raw_sha256"] == "abc"
    assert reloaded.get("phantom-uniform").provenance["status"] == "fetched"


def test_set_expected_writes_the_probe_block(manifest_file):
    m = load(manifest_file)
    m.set_expected("phantom-uniform", {
        "axes": "CYX", "shape": [2, 64, 64], "dtype": "uint16",
        "size_c": 2, "pixel_size_um": 0.69, "reader": "bioio_tifffile",
    })
    m.save()
    assert load(manifest_file).get("phantom-uniform").expected["axes"] == "CYX"


def test_validate_rejects_a_licence_partition_mismatch(manifest_file):
    m = load(manifest_file)
    e = m.get("phantom-uniform")
    e.partition = "commercial-safe"
    e.access = "PRIVATE"
    with pytest.raises(ManifestError, match="partition"):
        validate_entry(e)


def test_validate_rejects_retain_raw_false(manifest_file):
    m = load(manifest_file)
    e = m.get("phantom-uniform")
    e.retain_raw = False
    with pytest.raises(ManifestError, match="retain_raw"):
        validate_entry(e)


def test_validate_requires_a_source_locator(manifest_file):
    m = load(manifest_file)
    e = m.get("phantom-uniform")
    e.source = {"kind": "http"}
    with pytest.raises(ManifestError, match="url"):
        validate_entry(e)
